firstName = input("Cual es tu nombre: ")
lastName = input("Cual es tu apellido: ")
seccion = input("Cual es tu seccion: ")
sede = input("Cual es tu sede: ")
print("Hola " + firstName, lastName +" Tu seccion es "+ seccion +" y tu sede es "+ sede)